// 全局
export const SET_HISTROY_URL = 'SET_HISTROY_URL'
export const SET_BREADITEM_ARRAY = 'SET_BREADITEM_ARRAY'
export const START_FETCH_DATA = 'START_FETCH_DATA'
export const STOP_FETCH_DATA = 'STOP_FETCH_DATA'

// 用户
export const SET_EREK_USER_INFO = 'SET_EREK_USER_INFO'

// 标准列表
export const SET_STAND_FETCH_STATUS = 'SET_STAND_FETCH_STATUS'
export const RETRIEVE_TASK_LIST = 'RETRIEVE_TASK_LIST'
export const RETRIEVE_STANDARD_LIST = 'RETRIEVE_STANDARD_LIST'

// 表哥列表
export const SET_TABLE_FETCH_STATUS = 'SET_TABLE_FETCH_STATUS'
export const RETRIEVE_TABLE_LIST = 'RETRIEVE_TABLE_LIST'
